language: python
python:
  - "3.6"
cache:
  - pip
before_install:
  # install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION coveralls
  - source activate test-environment
  # now we are in an environment
  - conda install -c potassco clingo
  - pip install -r requirements.txt
  - pip install -e .
script:
  - python setup.py test
